name: dotnet-format

on:
    push:
      branches:
        - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies and build
        run: |
            npm install
            npm build        

      - name: Start server
        run: npm run dev --production

  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Check code formatting
        run: |
          npm install -g editorconfig-checker
          editorconfig-checker --exclude "node_modules/**"
